### ISSUE TITLE
Settings to setup the dates like you want them

### ISSUE THREAD

**Issue by itssimple** [MultinetInteractive/EduAdmin-WordPress#358]
# The problem

A lot of different customers want their dates shown in different ways, and now we have started noticing clashes between different types where people use both events without course days, and with course days (which has different formatting)

So, I think it's time that we collect all these issues and create a setting page just for date formatting throughout the entire plugin.

We need to create a date format settings page in the WordPress plugin, that lets the user select how they want to format dates for different kind of scenarios.

## The subtasks we need to solve

- [x] #254 Show the same layout for coursedays, both with continuous dates with the same start and end time and with different times
- [x] #354 Always show course days as number of days instead of grouping them
- [x] #356 Remove name of weekday from eventdates
- [x] #51 Date format settings

# Types of dates we're showing

## Event dates (when the course doesn't have any registered separate days)

By default, when we're just dealing with start and end date, we display it without weekdays and with long month names.

## Course days (when a event contains multiple separate days)

If a event contains event dates (course days), we try to show it in different ways depending on how many logical groups we can create from the days.

And if the amount of dates are more than 3, we always use the short format for day/months and include the days (mon-sun)

If it's only a single day, we output it as such, with inherited settings, otherwise we calculate logical groups of dates based on consecutive/repeating dates with the same start/end time.

And if we end up with more than 3 of these groups, we also create a small schedule pop up that shows us all groups, and then just output the total number of days between the start and end date.

## Programme courses, with possibility to course days in all separate courses during the programme

For programmes we have it even more mixed up, where we first based on the events in the programme start, collect all events that share the same date period, to catch events occurring on the same day, and then based on that, we check for eventdates to see if we should output every separate date, or just the start and end date of the event into the "schedule" popup.

# Code that needs fixing (for display)

```plain
content/template/bookingTemplate/event-selector.php
content/template/bookingTemplate/participants/contact-participant.php
content/template/bookingTemplate/participants/participant-template.php
content/template/detailTemplate/blocks/event-item.php
content/template/interestRegTemplate/interest-reg-event.php
content/template/listTemplate/blocks/event-block-a.php
content/template/listTemplate/blocks/event-block-b.php
content/template/myPagesTemplate/bookings.php
content/template/programme/template/detail-list.php
```

(And these are just the ones showing the dates I'm giving example of right now)

# Suggested fix to handle these issues

Rewrite date handling as a separate class, with customizable date format for each output (show preview in settings page).

If we create a new settings page in the admin section to handle this, we could have our users configure how they want to format things, if they always want a specific format regardless on how many logical groups or days they have.

I.E. if you always want the schedule pop up to be visible, you should be able to select that.

And then we should allow users to select if they want long/short format for day/month names.
